server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: Second-hand-trading-platform

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/second_hand_trade?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: b8t{TUNu|7]A

  sql:
    init:
      mode: never

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

app:
  upload:
    dir: /opt/app/uploads
  jwt:
    secret: 换成你自定义的复杂随机字符串
    expire-minutes: 120
  payment:
    return-url: http://114.132.69.232/orders
    alipay:
      enabled: false
      gateway: https://openapi.alipay.com/gateway.do
      app-id:
      private-key:
      notify-url: http://114.132.69.232/api/payments/alipay/notify
      return-url: http://114.132.69.232/orders
    wechat:
      enabled: false
      gateway: https://api.mch.weixin.qq.com
      app-id:
      mch-id:
      merchant-serial-no:
      private-key:
      notify-url: http://114.132.69.232/api/payments/wechat/notify